apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-volume-claim
  namespace: gitea
  labels:
    app: gitea
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-durable
  resources:
    requests:
      storage: 10Gi