apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: modify-pvs-to-sa
  namespace: postgresql
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
subjects:
  - kind: ServiceAccount
    name: recover-volume-hook
    namespace: postgresql
roleRef:
  kind: ClusterRole
  name: modify-pvs
  apiGroup: rbac.authorization.k8s.io