apiVersion: v1
kind: ServiceAccount
metadata:
  name: recover-volume-hook
  namespace: gitea
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
