apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:k3s-argocd-cluster/bootstrap-k3s.git'
    path: infrastructure
    targetRevision: master
  destination:
    namespace: infrastructure
    name: in-cluster
  syncPolicy:
    automated: {}
