apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: argocd/overlays/k3s
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: argocd
    name: {{ .Values.spec.destination.name }}
  syncPolicy:
    automated: {}