apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: gitea/overlays/k3s
    targetRevision: {{ .Values.spec.source.targetRevision }}
    plugin:
      env:
        - name: MAIN_HELM_CHART_DIR
          value: '../../base/charts/gitea'
  destination:
    namespace: gitea
    name: {{ .Values.spec.destination.name }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true