apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iobroker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: iobroker/overlays/k3s
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: iobroker
    name: {{ .Values.spec.destination.name }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true