apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: netdata
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: netdata
    name: {{ .Values.spec.destination.name }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true