apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: postgresql/overlays/k3s
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: postgresql
    name: {{ .Values.spec.destination.name }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true