apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: sealedsecrets/overlays/k3s
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: kube-system
    name: {{ .Values.spec.destination.name }}
  syncPolicy:
    automated: {}