apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: traefik
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    namespace: traefik
    name: {{ .Values.spec.destination.name }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true