apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: postgresql
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-durable
  resources:
    requests:
      storage: 10Gi