apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-listener
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-listener-binding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-listener
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-listener-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-listener
  namespace: tekton
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles