apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: duplicati-volume-claim
  namespace: duplicati
  labels:
    app: duplicati
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-durable
  resources:
    requests:
      storage: 10Gi