apiVersion: v1
kind: Service
metadata:
  name: duplicati
  namespace: duplicati
  labels:
    app.kubernetes.io/instance: duplicati
    app.kubernetes.io/name: duplicati
spec:
  selector:
    app.kubernetes.io/instance: duplicati-duplicati
    app.kubernetes.io/name: duplicati
  ports:
  - name: duplicati
    protocol: TCP
    port: 8200
    targetPort: duplicati
  type: ClusterIP
  clusterIP: None